// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8BxrVwWbfrz7VXFDrbW31oISfE6Mkxgg',
    appId: '1:956187631109:web:03400ec037d7accfd1866c',
    messagingSenderId: '956187631109',
    projectId: 'moviebox-c6a75',
    authDomain: 'moviebox-c6a75.firebaseapp.com',
    databaseURL: 'https://moviebox-c6a75-default-rtdb.firebaseio.com',
    storageBucket: 'moviebox-c6a75.appspot.com',
    measurementId: 'G-BNG5W235B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP97HJdSZheDt6GFBGRDy0JJYK8HsiHRQ',
    appId: '1:956187631109:android:536a898a5e89ecffd1866c',
    messagingSenderId: '956187631109',
    projectId: 'moviebox-c6a75',
    databaseURL: 'https://moviebox-c6a75-default-rtdb.firebaseio.com',
    storageBucket: 'moviebox-c6a75.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRRKWYlySnVhXwo9yUycxM0tGilOS9pIE',
    appId: '1:956187631109:ios:41ad3f45d8c7bf1dd1866c',
    messagingSenderId: '956187631109',
    projectId: 'moviebox-c6a75',
    databaseURL: 'https://moviebox-c6a75-default-rtdb.firebaseio.com',
    storageBucket: 'moviebox-c6a75.appspot.com',
    iosBundleId: 'com.example.testes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8BxrVwWbfrz7VXFDrbW31oISfE6Mkxgg',
    appId: '1:956187631109:web:5ccd9e2ba5b08f78d1866c',
    messagingSenderId: '956187631109',
    projectId: 'moviebox-c6a75',
    authDomain: 'moviebox-c6a75.firebaseapp.com',
    databaseURL: 'https://moviebox-c6a75-default-rtdb.firebaseio.com',
    storageBucket: 'moviebox-c6a75.appspot.com',
    measurementId: 'G-RF8BZ7DRFP',
  );

}